// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://poehzhurxmgieitrcfkk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBvZWh6aHVyeG1naWVpdHJjZmtrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3NTczODAsImV4cCI6MjA1OTMzMzM4MH0.SazCkJYUwMXZpCSGAD2V_E5DPkUY-zGU1TJe71wgMas";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);